// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file protos/music/music.proto (package music, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file protos/music/music.proto.
 */
export const file_protos_music_music: GenFile = /*@__PURE__*/
  fileDesc("Chhwcm90b3MvbXVzaWMvbXVzaWMucHJvdG8SBW11c2ljIkMKDFBsYXlNdXNpY1JlcRIPCgdnYW1lX2lkGAEgASgJEiIKBmVmZmVjdBgCIAEoDjISLm11c2ljLlNvdW5kRWZmZWN0IiYKDVBsYXlNdXNpY1Jlc3ASFQoNYXVkaW9fcGF5bG9hZBgBIAEoDCo1CgtTb3VuZEVmZmVjdBIICgRKVU1QEAASEwoPU0NPUkVfSU5DUkVBU0VEEAESBwoDRElFEAIySgoMTXVzaWNTZXJ2aWNlEjoKCVBsYXlNdXNpYxITLm11c2ljLlBsYXlNdXNpY1JlcRoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSIAQgxaCi4vO211c2ljcGJiBnByb3RvMw", [file_google_protobuf_empty]);

/**
 * @generated from message music.PlayMusicReq
 */
export type PlayMusicReq = Message<"music.PlayMusicReq"> & {
  /**
   * @generated from field: string game_id = 1;
   */
  gameId: string;

  /**
   * @generated from field: music.SoundEffect effect = 2;
   */
  effect: SoundEffect;
};

/**
 * Describes the message music.PlayMusicReq.
 * Use `create(PlayMusicReqSchema)` to create a new message.
 */
export const PlayMusicReqSchema: GenMessage<PlayMusicReq> = /*@__PURE__*/
  messageDesc(file_protos_music_music, 0);

/**
 * @generated from message music.PlayMusicResp
 */
export type PlayMusicResp = Message<"music.PlayMusicResp"> & {
  /**
   * @generated from field: bytes audio_payload = 1;
   */
  audioPayload: Uint8Array;
};

/**
 * Describes the message music.PlayMusicResp.
 * Use `create(PlayMusicRespSchema)` to create a new message.
 */
export const PlayMusicRespSchema: GenMessage<PlayMusicResp> = /*@__PURE__*/
  messageDesc(file_protos_music_music, 1);

/**
 * @generated from enum music.SoundEffect
 */
export enum SoundEffect {
  /**
   * @generated from enum value: JUMP = 0;
   */
  JUMP = 0,

  /**
   * @generated from enum value: SCORE_INCREASED = 1;
   */
  SCORE_INCREASED = 1,

  /**
   * @generated from enum value: DIE = 2;
   */
  DIE = 2,
}

/**
 * Describes the enum music.SoundEffect.
 */
export const SoundEffectSchema: GenEnum<SoundEffect> = /*@__PURE__*/
  enumDesc(file_protos_music_music, 0);

/**
 * @generated from service music.MusicService
 */
export const MusicService: GenService<{
  /**
   * @generated from rpc music.MusicService.PlayMusic
   */
  playMusic: {
    methodKind: "unary";
    input: typeof PlayMusicReqSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_protos_music_music, 0);

