// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file protos/world_gen/world_gen.proto (package world_gen, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file protos/world_gen/world_gen.proto.
 */
export const file_protos_world_gen_world_gen: GenFile = /*@__PURE__*/
  fileDesc("CiBwcm90b3Mvd29ybGRfZ2VuL3dvcmxkX2dlbi5wcm90bxIJd29ybGRfZ2VuIk8KC1dvcmxkR2VuUmVxEg8KB2dhbWVfaWQYASABKAkSFgoOdmlld3BvcnRfd2lkdGgYAiABKAUSFwoPdmlld3BvcnRfaGVpZ2h0GAMgASgFIjEKCFBpcGVTcGVjEhEKCWdhcF9zdGFydBgBIAEoARISCgpnYXBfaGVpZ2h0GAIgASgBIk8KDldvcmxkR2VuZXJhdGVkEhQKDHBpcGVfc3BhY2luZxgBIAEoARInCgpwaXBlX3NwZWNzGAIgAygLMhMud29ybGRfZ2VuLlBpcGVTcGVjMlcKD1dvcmxkR2VuU2VydmljZRJECg1HZW5lcmF0ZVdvcmxkEhYud29ybGRfZ2VuLldvcmxkR2VuUmVxGhkud29ybGRfZ2VuLldvcmxkR2VuZXJhdGVkIgBCOVo3Z2l0aHViLmNvbS95dXY0MTgvY3M1NTNwcm9qZWN0L2JhY2tlbmQvcHJvdG9zL3dvcmxkX2dlbmIGcHJvdG8z");

/**
 * @generated from message world_gen.WorldGenReq
 */
export type WorldGenReq = Message<"world_gen.WorldGenReq"> & {
  /**
   * @generated from field: string game_id = 1;
   */
  gameId: string;

  /**
   * @generated from field: int32 viewport_width = 2;
   */
  viewportWidth: number;

  /**
   * @generated from field: int32 viewport_height = 3;
   */
  viewportHeight: number;
};

/**
 * Describes the message world_gen.WorldGenReq.
 * Use `create(WorldGenReqSchema)` to create a new message.
 */
export const WorldGenReqSchema: GenMessage<WorldGenReq> = /*@__PURE__*/
  messageDesc(file_protos_world_gen_world_gen, 0);

/**
 * @generated from message world_gen.PipeSpec
 */
export type PipeSpec = Message<"world_gen.PipeSpec"> & {
  /**
   * @generated from field: double gap_start = 1;
   */
  gapStart: number;

  /**
   *  |      |
   *  |      |
   *  |      |
   *  |      |  <- Gap start
   *                  |
   *                  |
   *                  |    -> gap height
   *                  |
   *                  |
   *  |      | <- gap start + gap height
   *  |      |
   *  |      |
   *  |      |
   *
   * @generated from field: double gap_height = 2;
   */
  gapHeight: number;
};

/**
 * Describes the message world_gen.PipeSpec.
 * Use `create(PipeSpecSchema)` to create a new message.
 */
export const PipeSpecSchema: GenMessage<PipeSpec> = /*@__PURE__*/
  messageDesc(file_protos_world_gen_world_gen, 1);

/**
 * Everything here is in terms of percentages
 *
 * @generated from message world_gen.WorldGenerated
 */
export type WorldGenerated = Message<"world_gen.WorldGenerated"> & {
  /**
   * Spacing between pipes on x axis
   *
   * @generated from field: double pipe_spacing = 1;
   */
  pipeSpacing: number;

  /**
   * @generated from field: repeated world_gen.PipeSpec pipe_specs = 2;
   */
  pipeSpecs: PipeSpec[];
};

/**
 * Describes the message world_gen.WorldGenerated.
 * Use `create(WorldGeneratedSchema)` to create a new message.
 */
export const WorldGeneratedSchema: GenMessage<WorldGenerated> = /*@__PURE__*/
  messageDesc(file_protos_world_gen_world_gen, 2);

/**
 * @generated from service world_gen.WorldGenService
 */
export const WorldGenService: GenService<{
  /**
   * @generated from rpc world_gen.WorldGenService.GenerateWorld
   */
  generateWorld: {
    methodKind: "unary";
    input: typeof WorldGenReqSchema;
    output: typeof WorldGeneratedSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_protos_world_gen_world_gen, 0);

