// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file protos/game_engine/game_engine.proto (package game_engine, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { WorldGenerated } from "../world_gen/world_gen_pb";
import { file_protos_world_gen_world_gen } from "../world_gen/world_gen_pb";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file protos/game_engine/game_engine.proto.
 */
export const file_protos_game_engine_game_engine: GenFile = /*@__PURE__*/
  fileDesc("CiRwcm90b3MvZ2FtZV9lbmdpbmUvZ2FtZV9lbmdpbmUucHJvdG8SC2dhbWVfZW5naW5lIkQKEkdhbWVFbmdpbmVJbnB1dFJlcRIPCgdnYW1lX2lkGAIgASgJEh0KA2tleRgDIAEoDjIQLmdhbWVfZW5naW5lLktleSKAAQoSR2FtZUVuZ2luZVN0YXJ0UmVxEg8KB2dhbWVfaWQYAiABKAkSFgoOdmlld3BvcnRfd2lkdGgYAyABKAUSFwoPdmlld3BvcnRfaGVpZ2h0GAQgASgFEigKBXdvcmxkGAUgASgLMhkud29ybGRfZ2VuLldvcmxkR2VuZXJhdGVkKhAKA0tleRIJCgVTUEFDRRAAMqUBChFHYW1lRW5naW5lU2VydmljZRJICgtIYW5kbGVJbnB1dBIfLmdhbWVfZW5naW5lLkdhbWVFbmdpbmVJbnB1dFJlcRoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSIAEkYKCVN0YXJ0R2FtZRIfLmdhbWVfZW5naW5lLkdhbWVFbmdpbmVTdGFydFJlcRoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSIAQjtaOWdpdGh1Yi5jb20veXV2NDE4L2NzNTUzcHJvamVjdC9iYWNrZW5kL3Byb3Rvcy9nYW1lX2VuZ2luZWIGcHJvdG8z", [file_protos_world_gen_world_gen, file_google_protobuf_empty]);

/**
 * @generated from message game_engine.GameEngineInputReq
 */
export type GameEngineInputReq = Message<"game_engine.GameEngineInputReq"> & {
  /**
   * @generated from field: string game_id = 2;
   */
  gameId: string;

  /**
   * @generated from field: game_engine.Key key = 3;
   */
  key: Key;
};

/**
 * Describes the message game_engine.GameEngineInputReq.
 * Use `create(GameEngineInputReqSchema)` to create a new message.
 */
export const GameEngineInputReqSchema: GenMessage<GameEngineInputReq> = /*@__PURE__*/
  messageDesc(file_protos_game_engine_game_engine, 0);

/**
 * @generated from message game_engine.GameEngineStartReq
 */
export type GameEngineStartReq = Message<"game_engine.GameEngineStartReq"> & {
  /**
   * @generated from field: string game_id = 2;
   */
  gameId: string;

  /**
   * @generated from field: int32 viewport_width = 3;
   */
  viewportWidth: number;

  /**
   * @generated from field: int32 viewport_height = 4;
   */
  viewportHeight: number;

  /**
   * @generated from field: world_gen.WorldGenerated world = 5;
   */
  world?: WorldGenerated;
};

/**
 * Describes the message game_engine.GameEngineStartReq.
 * Use `create(GameEngineStartReqSchema)` to create a new message.
 */
export const GameEngineStartReqSchema: GenMessage<GameEngineStartReq> = /*@__PURE__*/
  messageDesc(file_protos_game_engine_game_engine, 1);

/**
 * @generated from enum game_engine.Key
 */
export enum Key {
  /**
   * @generated from enum value: SPACE = 0;
   */
  SPACE = 0,
}

/**
 * Describes the enum game_engine.Key.
 */
export const KeySchema: GenEnum<Key> = /*@__PURE__*/
  enumDesc(file_protos_game_engine_game_engine, 0);

/**
 * Won't do anything on failure other than reject the requests.
 *
 * @generated from service game_engine.GameEngineService
 */
export const GameEngineService: GenService<{
  /**
   * @generated from rpc game_engine.GameEngineService.HandleInput
   */
  handleInput: {
    methodKind: "unary";
    input: typeof GameEngineInputReqSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc game_engine.GameEngineService.StartGame
   */
  startGame: {
    methodKind: "unary";
    input: typeof GameEngineStartReqSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_protos_game_engine_game_engine, 0);

