// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: protos/auth/auth.proto

package auth_svc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_protos_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_protos_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JwtToken      string                 `protobuf:"bytes,1,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"` // Remove optional since Connect handles nullability differently
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_protos_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_protos_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthResponse) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

var File_protos_auth_auth_proto protoreflect.FileDescriptor

const file_protos_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x16protos/auth/auth.proto\x12\x04auth\"E\n" +
	"\vAuthRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"+\n" +
	"\fAuthResponse\x12\x1b\n" +
	"\tjwt_token\x18\x01 \x01(\tR\bjwtToken2D\n" +
	"\vAuthService\x125\n" +
	"\fAuthenticate\x12\x11.auth.AuthRequest\x1a\x12.auth.AuthResponseB\rZ\v./;auth_svcb\x06proto3"

var (
	file_protos_auth_auth_proto_rawDescOnce sync.Once
	file_protos_auth_auth_proto_rawDescData []byte
)

func file_protos_auth_auth_proto_rawDescGZIP() []byte {
	file_protos_auth_auth_proto_rawDescOnce.Do(func() {
		file_protos_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_auth_auth_proto_rawDesc), len(file_protos_auth_auth_proto_rawDesc)))
	})
	return file_protos_auth_auth_proto_rawDescData
}

var file_protos_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_auth_auth_proto_goTypes = []any{
	(*AuthRequest)(nil),  // 0: auth.AuthRequest
	(*AuthResponse)(nil), // 1: auth.AuthResponse
}
var file_protos_auth_auth_proto_depIdxs = []int32{
	0, // 0: auth.AuthService.Authenticate:input_type -> auth.AuthRequest
	1, // 1: auth.AuthService.Authenticate:output_type -> auth.AuthResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_auth_auth_proto_init() }
func file_protos_auth_auth_proto_init() {
	if File_protos_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_auth_auth_proto_rawDesc), len(file_protos_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_auth_auth_proto_goTypes,
		DependencyIndexes: file_protos_auth_auth_proto_depIdxs,
		MessageInfos:      file_protos_auth_auth_proto_msgTypes,
	}.Build()
	File_protos_auth_auth_proto = out.File
	file_protos_auth_auth_proto_goTypes = nil
	file_protos_auth_auth_proto_depIdxs = nil
}
