// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file protos/initiator/initiator.proto (package initiator, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file protos/initiator/initiator.proto.
 */
export const file_protos_initiator_initiator: GenFile = /*@__PURE__*/
  fileDesc("CiBwcm90b3MvaW5pdGlhdG9yL2luaXRpYXRvci5wcm90bxIJaW5pdGlhdG9yInUKDFN0YXJ0R2FtZVJlcRILCgNqd3QYASABKAkSFgoOdmlld3BvcnRfd2lkdGgYAiABKAUSFwoPdmlld3BvcnRfaGVpZ2h0GAMgASgFEhIKCmJpcmRfd2lkdGgYBCABKAUSEwoLYmlyZF9oZWlnaHQYBSABKAUiIAoNU3RhcnRHYW1lUmVzcBIPCgdnYW1lX2lkGAEgASgJMlQKEEluaXRpYXRvclNlcnZpY2USQAoJU3RhcnRHYW1lEhcuaW5pdGlhdG9yLlN0YXJ0R2FtZVJlcRoYLmluaXRpYXRvci5TdGFydEdhbWVSZXNwIgBCEFoOLi87aW5pdGlhdG9ycGJiBnByb3RvMw");

/**
 * @generated from message initiator.StartGameReq
 */
export type StartGameReq = Message<"initiator.StartGameReq"> & {
  /**
   * @generated from field: string jwt = 1;
   */
  jwt: string;

  /**
   * @generated from field: int32 viewport_width = 2;
   */
  viewportWidth: number;

  /**
   * @generated from field: int32 viewport_height = 3;
   */
  viewportHeight: number;

  /**
   * @generated from field: int32 bird_width = 4;
   */
  birdWidth: number;

  /**
   * @generated from field: int32 bird_height = 5;
   */
  birdHeight: number;
};

/**
 * Describes the message initiator.StartGameReq.
 * Use `create(StartGameReqSchema)` to create a new message.
 */
export const StartGameReqSchema: GenMessage<StartGameReq> = /*@__PURE__*/
  messageDesc(file_protos_initiator_initiator, 0);

/**
 * @generated from message initiator.StartGameResp
 */
export type StartGameResp = Message<"initiator.StartGameResp"> & {
  /**
   * @generated from field: string game_id = 1;
   */
  gameId: string;
};

/**
 * Describes the message initiator.StartGameResp.
 * Use `create(StartGameRespSchema)` to create a new message.
 */
export const StartGameRespSchema: GenMessage<StartGameResp> = /*@__PURE__*/
  messageDesc(file_protos_initiator_initiator, 1);

/**
 * @generated from service initiator.InitiatorService
 */
export const InitiatorService: GenService<{
  /**
   * @generated from rpc initiator.InitiatorService.StartGame
   */
  startGame: {
    methodKind: "unary";
    input: typeof StartGameReqSchema;
    output: typeof StartGameRespSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_protos_initiator_initiator, 0);

