// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file protos/music/music.proto (package music, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file protos/music/music.proto.
 */
export const file_protos_music_music: GenFile = /*@__PURE__*/
  fileDesc("Chhwcm90b3MvbXVzaWMvbXVzaWMucHJvdG8SBW11c2ljIkMKDFBsYXlNdXNpY1JlcRIPCgdnYW1lX2lkGAEgASgJEiIKBmVmZmVjdBgCIAEoDjISLm11c2ljLlNvdW5kRWZmZWN0IiUKDVBsYXlNdXNpY1Jlc3ASFAoMb3B1c19wYXlsb2FkGAEgASgMKjUKC1NvdW5kRWZmZWN0EggKBEpVTVAQABITCg9TQ09SRV9JTkNSRUFTRUQQARIHCgNESUUQAjJICgxNdXNpY1NlcnZpY2USOAoJUGxheU11c2ljEhMubXVzaWMuUGxheU11c2ljUmVxGhQubXVzaWMuUGxheU11c2ljUmVzcCIAQgxaCi4vO211c2ljcGJiBnByb3RvMw");

/**
 * @generated from message music.PlayMusicReq
 */
export type PlayMusicReq = Message<"music.PlayMusicReq"> & {
  /**
   * @generated from field: string game_id = 1;
   */
  gameId: string;

  /**
   * @generated from field: music.SoundEffect effect = 2;
   */
  effect: SoundEffect;
};

/**
 * Describes the message music.PlayMusicReq.
 * Use `create(PlayMusicReqSchema)` to create a new message.
 */
export const PlayMusicReqSchema: GenMessage<PlayMusicReq> = /*@__PURE__*/
  messageDesc(file_protos_music_music, 0);

/**
 * @generated from message music.PlayMusicResp
 */
export type PlayMusicResp = Message<"music.PlayMusicResp"> & {
  /**
   * @generated from field: bytes opus_payload = 1;
   */
  opusPayload: Uint8Array;
};

/**
 * Describes the message music.PlayMusicResp.
 * Use `create(PlayMusicRespSchema)` to create a new message.
 */
export const PlayMusicRespSchema: GenMessage<PlayMusicResp> = /*@__PURE__*/
  messageDesc(file_protos_music_music, 1);

/**
 * @generated from enum music.SoundEffect
 */
export enum SoundEffect {
  /**
   * @generated from enum value: JUMP = 0;
   */
  JUMP = 0,

  /**
   * @generated from enum value: SCORE_INCREASED = 1;
   */
  SCORE_INCREASED = 1,

  /**
   * @generated from enum value: DIE = 2;
   */
  DIE = 2,
}

/**
 * Describes the enum music.SoundEffect.
 */
export const SoundEffectSchema: GenEnum<SoundEffect> = /*@__PURE__*/
  enumDesc(file_protos_music_music, 0);

/**
 * @generated from service music.MusicService
 */
export const MusicService: GenService<{
  /**
   * @generated from rpc music.MusicService.PlayMusic
   */
  playMusic: {
    methodKind: "unary";
    input: typeof PlayMusicReqSchema;
    output: typeof PlayMusicRespSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_protos_music_music, 0);

