// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: proto/music.proto

package musicpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SoundEffect int32

const (
	SoundEffect_JUMP            SoundEffect = 0
	SoundEffect_SCORE_INCREASED SoundEffect = 1
	SoundEffect_DIE             SoundEffect = 2
)

// Enum value maps for SoundEffect.
var (
	SoundEffect_name = map[int32]string{
		0: "JUMP",
		1: "SCORE_INCREASED",
		2: "DIE",
	}
	SoundEffect_value = map[string]int32{
		"JUMP":            0,
		"SCORE_INCREASED": 1,
		"DIE":             2,
	}
)

func (x SoundEffect) Enum() *SoundEffect {
	p := new(SoundEffect)
	*p = x
	return p
}

func (x SoundEffect) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SoundEffect) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_music_proto_enumTypes[0].Descriptor()
}

func (SoundEffect) Type() protoreflect.EnumType {
	return &file_proto_music_proto_enumTypes[0]
}

func (x SoundEffect) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SoundEffect.Descriptor instead.
func (SoundEffect) EnumDescriptor() ([]byte, []int) {
	return file_proto_music_proto_rawDescGZIP(), []int{0}
}

type PlayMusicReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Effect        SoundEffect            `protobuf:"varint,2,opt,name=effect,proto3,enum=music.SoundEffect" json:"effect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayMusicReq) Reset() {
	*x = PlayMusicReq{}
	mi := &file_proto_music_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayMusicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayMusicReq) ProtoMessage() {}

func (x *PlayMusicReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_music_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayMusicReq.ProtoReflect.Descriptor instead.
func (*PlayMusicReq) Descriptor() ([]byte, []int) {
	return file_proto_music_proto_rawDescGZIP(), []int{0}
}

func (x *PlayMusicReq) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PlayMusicReq) GetEffect() SoundEffect {
	if x != nil {
		return x.Effect
	}
	return SoundEffect_JUMP
}

type PlayMusicResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpusPayload   []byte                 `protobuf:"bytes,1,opt,name=opus_payload,json=opusPayload,proto3" json:"opus_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayMusicResp) Reset() {
	*x = PlayMusicResp{}
	mi := &file_proto_music_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayMusicResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayMusicResp) ProtoMessage() {}

func (x *PlayMusicResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_music_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayMusicResp.ProtoReflect.Descriptor instead.
func (*PlayMusicResp) Descriptor() ([]byte, []int) {
	return file_proto_music_proto_rawDescGZIP(), []int{1}
}

func (x *PlayMusicResp) GetOpusPayload() []byte {
	if x != nil {
		return x.OpusPayload
	}
	return nil
}

var File_proto_music_proto protoreflect.FileDescriptor

const file_proto_music_proto_rawDesc = "" +
	"\n" +
	"\x11proto/music.proto\x12\x05music\"S\n" +
	"\fPlayMusicReq\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12*\n" +
	"\x06effect\x18\x02 \x01(\x0e2\x12.music.SoundEffectR\x06effect\"2\n" +
	"\rPlayMusicResp\x12!\n" +
	"\fopus_payload\x18\x01 \x01(\fR\vopusPayload*5\n" +
	"\vSoundEffect\x12\b\n" +
	"\x04JUMP\x10\x00\x12\x13\n" +
	"\x0fSCORE_INCREASED\x10\x01\x12\a\n" +
	"\x03DIE\x10\x022H\n" +
	"\fMusicService\x128\n" +
	"\tPlayMusic\x12\x13.music.PlayMusicReq\x1a\x14.music.PlayMusicResp\"\x00B\fZ\n" +
	"./;musicpbb\x06proto3"

var (
	file_proto_music_proto_rawDescOnce sync.Once
	file_proto_music_proto_rawDescData []byte
)

func file_proto_music_proto_rawDescGZIP() []byte {
	file_proto_music_proto_rawDescOnce.Do(func() {
		file_proto_music_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_music_proto_rawDesc), len(file_proto_music_proto_rawDesc)))
	})
	return file_proto_music_proto_rawDescData
}

var file_proto_music_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_music_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_music_proto_goTypes = []any{
	(SoundEffect)(0),      // 0: music.SoundEffect
	(*PlayMusicReq)(nil),  // 1: music.PlayMusicReq
	(*PlayMusicResp)(nil), // 2: music.PlayMusicResp
}
var file_proto_music_proto_depIdxs = []int32{
	0, // 0: music.PlayMusicReq.effect:type_name -> music.SoundEffect
	1, // 1: music.MusicService.PlayMusic:input_type -> music.PlayMusicReq
	2, // 2: music.MusicService.PlayMusic:output_type -> music.PlayMusicResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_music_proto_init() }
func file_proto_music_proto_init() {
	if File_proto_music_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_music_proto_rawDesc), len(file_proto_music_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_music_proto_goTypes,
		DependencyIndexes: file_proto_music_proto_depIdxs,
		EnumInfos:         file_proto_music_proto_enumTypes,
		MessageInfos:      file_proto_music_proto_msgTypes,
	}.Build()
	File_proto_music_proto = out.File
	file_proto_music_proto_goTypes = nil
	file_proto_music_proto_depIdxs = nil
}
