// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file protos/score/score.proto (package score, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { EmptySchema, Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file protos/score/score.proto.
 */
export const file_protos_score_score: GenFile = /*@__PURE__*/
  fileDesc("Chhwcm90b3Mvc2NvcmUvc2NvcmUucHJvdG8SBXNjb3JlIoEBCgpTY29yZUVudHJ5Eg8KB2dhbWVfaWQYASABKAkSDQoFc2NvcmUYAiABKAUSLwoLZmluaXNoX3RpbWUYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEhUKCHVzZXJuYW1lGAQgASgJSACIAQFCCwoJX3VzZXJuYW1lIl4KDUdldFNjb3Jlc1Jlc3ASIgoHZW50cmllcxgBIAMoCzIRLnNjb3JlLlNjb3JlRW50cnkSKQoOZ2xvYmFsX2VudHJpZXMYAiADKAsyES5zY29yZS5TY29yZUVudHJ5MocBCgxTY29yZVNlcnZpY2USOgoLVXBkYXRlU2NvcmUSES5zY29yZS5TY29yZUVudHJ5GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5IgASOwoJR2V0U2NvcmVzEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GhQuc2NvcmUuR2V0U2NvcmVzUmVzcCIAQgxaCi4vO3Njb3JlcGJiBnByb3RvMw", [file_google_protobuf_empty, file_google_protobuf_timestamp]);

/**
 * https://stackoverflow.com/questions/3574716/date-and-time-type-for-use-with-protobuf
 *
 * @generated from message score.ScoreEntry
 */
export type ScoreEntry = Message<"score.ScoreEntry"> & {
  /**
   * @generated from field: string game_id = 1;
   */
  gameId: string;

  /**
   * @generated from field: int32 score = 2;
   */
  score: number;

  /**
   * @generated from field: google.protobuf.Timestamp finish_time = 3;
   */
  finishTime?: Timestamp;

  /**
   * @generated from field: optional string username = 4;
   */
  username?: string;
};

/**
 * Describes the message score.ScoreEntry.
 * Use `create(ScoreEntrySchema)` to create a new message.
 */
export const ScoreEntrySchema: GenMessage<ScoreEntry> = /*@__PURE__*/
  messageDesc(file_protos_score_score, 0);

/**
 * @generated from message score.GetScoresResp
 */
export type GetScoresResp = Message<"score.GetScoresResp"> & {
  /**
   * @generated from field: repeated score.ScoreEntry entries = 1;
   */
  entries: ScoreEntry[];

  /**
   * @generated from field: repeated score.ScoreEntry global_entries = 2;
   */
  globalEntries: ScoreEntry[];
};

/**
 * Describes the message score.GetScoresResp.
 * Use `create(GetScoresRespSchema)` to create a new message.
 */
export const GetScoresRespSchema: GenMessage<GetScoresResp> = /*@__PURE__*/
  messageDesc(file_protos_score_score, 1);

/**
 * @generated from service score.ScoreService
 */
export const ScoreService: GenService<{
  /**
   * @generated from rpc score.ScoreService.UpdateScore
   */
  updateScore: {
    methodKind: "unary";
    input: typeof ScoreEntrySchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc score.ScoreService.GetScores
   */
  getScores: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof GetScoresRespSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_protos_score_score, 0);

